name: linguist_lang_info
description: >-
  A collection of language and content type information
  tracked by the linguist project.
version: 0.1.0-wip
repository: https://github.com/dart-community/linguist_lang_info

environment:
  sdk: ^3.6.0

dependencies:
  meta: ^1.12.0

dev_dependencies:
  build_runner: ^2.4.14
  checked_yaml: ^2.0.3
  code_builder: ^4.10.1
  dart_style: ^2.3.7
  json_annotation: ^4.9.0
  json_serializable: ^6.9.3
  night_raven_insight: ^3.0.0
  path: ^1.9.1
  test: ^1.25.14
  yaml: ^3.1.3
