name: linguist_lang_info
description: >-
  A collection of language and content type information
  tracked by the linguist project.
version: 0.2.0
repository: https://github.com/dart-community/linguist_lang_info

environment:
  sdk: ^3.8.0

dependencies:
  meta: ^1.15.0

dev_dependencies:
  build_runner: ^2.4.15
  checked_yaml: ^2.0.3
  code_builder: ^4.10.1
  dart_style: ^3.1.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  night_raven_insight: ^3.0.0
  path: ^1.9.1
  test: ^1.26.2
  yaml: ^3.1.3
