name: linguist_lang_info
description: >-
  A collection of language and content type information
  tracked by the linguist project.
version: 0.0.2-wip
repository: https://github.com/dart-community/linguist_lang_info

environment:
  sdk: ^3.2.0

dependencies:
  meta: ^1.11.0

dev_dependencies:
  build_runner: ^2.4.6
  checked_yaml: ^2.0.3
  code_builder: ^4.7.0
  dart_style: ^2.3.3
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  night_raven_insight: ^1.0.0
  path: ^1.8.3
  test: ^1.24.0
  yaml: ^3.1.2
